# Nombre de mi configuración
name: Node NoSQL API v2

# Eventos que detonarán el flujo de CI
on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - dev
#      - master

# Las tareas que va a ejecutar el flujo de CI
jobs:

  # Tarea para compilar el proyecto
  build:

    # Define sobre qué sistema operativo va a compilarse el proyecto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # version de github actions que usaremos
      - name: Login to Heroku Registry
        env:
          HEROKU_API_KEY: ${( secrets.HEROKU_API_KEY )}
        run: heroku container:Login
      - name: Build & push image
        run: |
              docker build . --tag nosql-api-v2 registry.heroku.com/${( secrets.HEROKU_APP_NAME)}/web nosql-api-v2 -f docker/prod/Dockerfile
              docker push registry.heroku.com/${( secrets.HEROKU_APP_NAME)}/web
      - name: realease
        run: heroku container:realease -a {( secrets.HEROKU_APP_NAME)} web

  # Tarea para ejecutar los tests del proyecto
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: API Tests
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test
